version: '3.1'
services:

  redis:
    image: redis
    container_name: redis-server
    ports:
      - 6379:6379
    networks:
      - redis-network

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
      - 6379:6379
  redis-slave-1:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6479:6379
    depends_on:
      - redis
    networks:
      - app-tier
  redis-slave-2:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6579:6379
    depends_on:
      - redis
    networks:
      - app-tier

  ewhaproject:
    image: gnidinger/ewha_project:1.0
    container_name: ewhaproject
    build: .
    restart: always
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - redis-network

networks:
  redis-network: